- name: create azure stuff
  ignore_errors: True
  gather_facts: false
  hosts: localhost
  tasks:

  - name: Remove resource group
    azure_rm_resourcegroup:
      name: Testing
      location: westus
      state: absent

  - name: Remove storage account
    azure_rm_storageaccount:
      resource_group: Testing
      name: testaccount001
      account_type: Standard_LRS
      state: absent
  
  - name: Remove virtual network
    azure_rm_virtualnetwork:
      resource_group: Testing
      name: testvn001
      address_prefixes: "10.10.0.0/16"
      state: absent
  
  - name: Add subnet
    azure_rm_subnet:
      resource_group: Testing
      name: subnet001
      address_prefix: "10.10.0.0/24"
      virtual_network: testvn001
      state: absent
  
  - name: Remove public ip
    azure_rm_publicipaddress:
      resource_group: Testing
      allocation_method: Static
      name: publicip001
      state: absent
  
  - name: Remove security group that allows SSH
    azure_rm_securitygroup:
      resource_group: Testing
      name: secgroup001
      state: absent
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Remove NIC
    azure_rm_networkinterface:
      resource_group: Testing
      name: testnic001
      virtual_network: testvn001
      subnet: subnet001
      public_ip_name: publicip001
      security_group: secgroup001
      state: absent

  - name: Remove virtual machine
    azure_rm_virtualmachine:
      resource_group: Testing
      name: testvm001
      vm_size: Standard_D1
      storage_account: testaccount001
      storage_container: testvm001
      storage_blob: testvm001.vhd
      admin_username: admin
      admin_password: Password!
      network_interfaces: testnic001
      state: absent
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
