---
- name: test aws inventory
  gather_facts: false
  hosts: all
  tasks:
    - name: run a command
      command: cat /etc/os-release
      register: result
    - debug:
        var: "{{ result }}"
