---
- name: Install custom facts
  hosts: all
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: listing68.fact
  tasks:
  - name: create remote directory
    file:
      state: directory
      recurse: yes
      path: "{{ remote_dir }}"
  - name: install new facts
    copy:
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"
