- name: using blocks
  hosts: all
  tasks:
    - name: intended to be successful
      block:
        - name: remove a file
          command:
            cmd: /usr/bin/rm /var/www/html/index.html
      rescue:
        - name: create a file
          command:
            cmd: /usr/bin/touch /tmp/rescuefile
      always:
        - name: always write a message to logs
          command:
            cmd: /usr/bin/logger hello

