---
- name: test register
  hosts: all
  vars_prompt:
    - name: username
      prompt: which user are you looking for
  tasks:
    - shell: cat /etc/passwd
      register: passwd_contents
    - debug:
        var: passwd_contents
    - debug: 
        msg: echo "passwd contains user {{ username }}"
      when: passwd_contents.stdout.find(username) != -1
