---
- name: using multiple conditions
  hosts: all
  tasks:
  - package:
      name: httpd
      state: installed
    when: 
      - ansible_distribution == "RedHat"
      - ansible_memfree_mb > 1512 
