- name: list instance facts
  hosts: localhost
  gather_facts: no
  become: no
  tasks:
  - name: Gather information about all instances
    community.aws.ec2_instance_info:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: us-west-2
    register: result
  - name: instances ID
    debug:
      msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }}"
    loop: "{{ result.instances }}"
