---
- hosts: localhost
  become: False
  tasks:
    - name: Create a pod
      k8s:
        state: present
        definition:
          api_version: v1
          kind: Pod
          metadata:
            name: ourfirstpod
            namespace: default
          spec:
            containers:
            - name: utilitypod
              image: nginx
